data:
  raw_path: data/raw/diabetes.csv


models:

  naive_bayes:
    type: "GaussianNB"
    params: {}
  
  logistic_regression:
    type: "LogisticRegression"
    params: {}

  decision_tree:
    type: "DecisionTreeClassifier"
    params: 
      max_depth: 10 

  random_forest:
    type: "RandomForestClassifier"
    params:
      n_estimators: 100
      max_depth: 10
      random_state: 42
